#include "device.h"

//_CONFIG2(POSCMOD_HS & DISUVREG_OFF & IOL1WAY_OFF & OSCIOFNC_OFF & FCKSM_CSECMD & FNOSC_PRIPLL & IESO_OFF & PLLDIV_NODIV);
//_CONFIG1(FWDTEN_OFF & ICS_PGx1 & COE_OFF & BKBUG_OFF & GWRP_ON & GCP_OFF & JTAGEN_OFF & GWRP_OFF);
